##### Workflow Configuration #####

###########
## Images #
###########
image_main: "docker://kevinlu366/bac-wgs-pipe:v1.0"
image_plsdb: "docker://kevinlu366/plsdb:2021_06_23_v2"
image_mob_suite: "docker://kevinlu366/mob_suite:3.1.0--pyhdfd78af_0"
image_platon: "docker://kevinlu366/platon:v1.6"
image_phigaro: "docker://kevinlu366/phigaro:2.3.0"
image_digis: "docker://kevinlu366/digis:v1.2"
image_gene_function: "docker://kevinlu366/gene_function:v1.0"
image_card_vfdb: "docker://kevinlu366/card_vfdb:v1.0"
image_signalp: "docker://kevinlu366/signalp:v6.0"
image_tmhmm: "docker://kevinlu366/tmhmm:v2.0c"

##############
# Data input #
##############
##### Sample list #####
# List of samples for analysis
sample_list: "config/sample_list.txt"
##### Sample info #####
# Genus of the strains. Please enter "Genus" if you don't have any target species to detect.
genus: "Genus"
# Species of the strains. Please enter "species" if you don't have any target species to detect.
species: "species"
##### Sequencing data source #####
# Sequencing data source options:
#   0: Illumina short reads + Long reads;
#   1: Long reads ONLY;
#   2: Illumina short reads ONLY)
seqdata_source: 1
# Illumina short reads
## Directory which stores input Illumina short-read data
illumina_data_dir: "path-to-short-read-data-dir"
## Illumina short-read fastq file name read id format (0: {sample}_1.fastq.gz; 1: {sample}_R1.fastq.gz)
illumina_fastq_read_id_format: 0
## Illumina short-read fastq file name suffix format (0: {sample}_1.fastq.gz; 1: {sample}_1.fq.gz)
illumina_fastq_suffix_format: 0
## Illumina short-read data directory format (0: {dir}/{sample}_1.fastq.gz; 1: {dir}/{sample}/{sample}_1.fastq.gz)
illumina_data_dir_format: 0
# Long reads (either PacBio or Nanopore)
## Directory which stores long-read data input
long_data_dir: "path-to-long-read-data-dir"
## Long-read fastq file name suffix format (0: {sample}.fastq.gz; 1: {sample}.fq.gz)
long_fastq_suffix_format: 0
## Long-read data directory format (0: {dir}/{sample}.fastq.gz; 1: {dir}/{sample}/{sample}.fastq.gz)
long_data_dir_format: 0

############
# Analysis #
############
##### Global #####
# Threads used by tools for each sample
threads: 16

##### Step 01. Raw sequencing reads QC and pre-processing #####
# Species identification (Kraken2 + Bracken)
## Kraken filter feature (Only qualified samples will run the rest of workflow) turn on/off (1/0)
##  This feature ONLY works with Illumina short reads
kraken2_filter: 0
## Kraken2 database (Standard: archaea, bacteria, viral, plasmid, human1, UniVec_Core PLUS protozoa & fungi)
kraken2_db: "path-to-Kraken2-database"
## Threshold (the minimum percentage of reads classified to target species)
kraken2_threshold: 50
## Bracken - level to estimate abundance
bracken_level: "S"
## Bracken - read length to get all classifications
bracken_read_len: 150

##### Step 03. Genome annotation and Genomic component analysis #####
# Plasmid
## PLSDB
### Maximal p-value to report in Mash screen
plsdb_max_pvalue: 0.99
### Minimal identity in Mash screen
plsdb_min_ident: 0.8
## Plasmidfinder
### Plasmidfinder parameters
#### Plasmidfinder minimum coverage (in decimals)
plasmidfinder_mincov: 0.65
#### Plasmidfinder minimum hreshold for identity (in decimals)
plasmidfinder_minid: 0.9

##### Step 04. Gene function analysis #####
# Gene function annotation
## EggNOG-mapper
### Path to eggNOG-mapper databases directory
eggnog_mapper_database: "path-to-EggNOG-mapper-database"
# Virulence or pathogenicity analysis
## VFDB database: Virulence factors (VF)
### VFDB blast parameters - minimum coverage
vfdb_blast_mincov: 80
### VFDB blast parameters - minimum hreshold for identity
vfdb_blast_minid: 90

##### Step 06. Genome Visualization #####
# Plasmid length threshold (MGCplotter might throw an error if it plots for very small plasmid)
plas_length_threshold: 3000
